classDiagram
    class Person {
        -String personName
        -String surname
        -date dayOfBirth
        -String phone
        -String email
    }

    class Employee {
        -integer employeeId
    }

    class Contractor

    class Intern {
        -double allowance
    }

    class Manager

    class Director

    class Contract {
        -date startDate
        -date endDate
        -double salary
    }

    class Project {
        -String projectName
        -double budget
    }

    class HRProject
    class BusinessProject
    class SoftwareProject

    class Department {
        -String departmentCode
    }

    class SkillWithLevel {
        -String level
    }

    class Skill {
        -String skillName
        -String category
    }

    Person <|-- Employee
    Person <|-- Contractor
    Person <|-- Intern
    Employee <|-- Manager
    Manager <|-- Director

    Project <|-- HRProject
    Project <|-- BusinessProject
    Project <|-- SoftwareProject

    Person "1" o-- "1..*" Contract : hasContract
    Person "1..*" o-- "*" Project : worksOn
    SkillWithLevel "*" --> "1" Employee : ofEmployee
    Project "*" o-- "*" SkillWithLevel : requiresSkill
    SkillWithLevel "1..*" --> "1" Skill : referencesSkill
    Manager "1" o-- "1..*" Employee : manages
    Department "1..*" --> "1" Director : hasLeader
    Employee "1..*" --> "1" Department : belongsTo
